server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka服务的名称
  cloud:
    config:
      server:
        git:
          # 这个uri用ssh地址一直都是无法访问，只有改成https地址加privateKey或者显示声明账号密码才有用
          uri: https://github.com/Xfengjin/springcloud-config.git #GitHub上的仓库名称
          # 搜索目录
          search-paths:
            - springcloud-config
          # 读取分支
          label: main
          force-pull: true
          username: XXXXXX #github账户
          password: XXXXXXX #github密码

#rabbitmq相关配置 使用： curl -X POST "http://localhost:3344/actutor/bus-refersh"  全局通知
  # curl -X POST "http://localhost:3344/actutor/bus-refersh/config-client:3355"  局部通知
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# rabbitmq相关配置，暴露Bus刷新配置端点
management:
  endpoints: # 暴露Bus刷新配置端点
    web:
      exposure:
        include: 'bus-refresh'