server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos服务的注册地址
        #server-addr: 192.168.0.20:1111
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用开始一次执行+1扫描，直至找到w未被占用的端口
        port: 8719
        datasource:
          ds1:
            nacos:
              server-addr: localhost:8848
              dataId: cloudalibaba-sentinel-service
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow

# nacos上的配置文件内容
              # [
                # {
                # "resource": "/rateLimit/byUrl", 资源名称
                # "limitApp": "default", 来源应用
                # "grade": 1, 阈值类型， 0表示线程数， 1表示QPS
                # "count": 1, 单机阈值
                # "strategy": 0, 流控模式 0表示直接， 1表示关联，2表示链路
                # "controlBehavior": 0, 流控效果 0表示快速失败， 1表示warn up, 2表示排队等待
              # "clusterMode": false 是否集群
              # }
              # ]

management:
  endpoints:
    web:
      exposure:
        include: "*"
